# Based on: https://github.com/microsoft/vscode-dev-containers/tree/main/containers/ubuntu

ARG VARIANT=ubuntu-22.04
# FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}
FROM ghcr.io/tigitlabs/nrf-docker

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>


