name: 'Smoke test'
inputs:
  image:
    description: 'Image to test'
    required: true
    default: 'base-ubuntu'
  variant:
    description: 'Variant to build and test'
    required: false

runs:
  using: composite
  steps:
    - name: Checkout main
      id: checkout_release
      uses: actions/checkout@v3
      with:
        repository: 'tigitlabs/dev-container'
        path: '__build'
        ref: 'main'

    - name: Build image
      id: build_image
      shell: bash
      run: |
        export VARIANT=${{ inputs.variant }}
        ${{ github.action_path }}/build.sh ${{ inputs.image }}

    - name: Test image
      id: test_image
      shell: bash
      run: ${{ github.action_path }}/test.sh  ${{ inputs.image }}
