version: 2.1

jobs:
  test:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      # Install make
      - run: apk add --no-cache bash
      - run: apk add --no-cache make
      - run: |
          export DOCKER_BUILDKIT=1
          docker build --platform=local -o . git://github.com/docker/buildx
          mkdir -p ~/.docker/cli-plugins
          mv buildx ~/.docker/cli-plugins/docker-buildx
      - run: make test-all-ci

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
