version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: make docker-build-ubuntu-base

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
