version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: |
          docker buildx build \
          --file .devcontainer/ubuntu-base/Dockerfile \
          --tag ghcr.io/tigitlabs/ubuntu-base:latest \
          --tag ghcr.io/tigitlabs/ubuntu-base:dev \
          .devcontainer/ubuntu-base/
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
