version: 2.1

jobs:
  test:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: make test-all-ci

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
