version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: make docker-build-all
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
