version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: make test-all-ci

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
