version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - checkout
      - - run: sudo apt-get update && sudo apt-get install -y make
      - run: make test-all-ci

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
