---

name: "Build-Test-Push"

on:
  workflow_call:
    inputs:
      image:
        description: 'Image to build'
        required: true
        type: string
      tag:
        description: 'Tag to apply to the image'
        required: true
        type: string
      registry:
        description: 'Registry to push to'
        required: false
        type: string
        default: 'ghcr.io'

jobs:
  build-devcontainer-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install devcontainer cli
        run: |
          npm install -g @devcontainers/cli
          devcontainer --version

      - name: Build the Ubuntu base image
        id: build_devcontainer_image
        run: |
          echo "Building the image: ${{ inputs.image }}:${{ inputs.tag }}"
          ./test/pre_build.sh ${{ inputs.image }} ${{ inputs.tag }}

      - name: Test the image
        id: test_base_ubuntu
        run: |
          echo "Testing the image"
          ./test/test_build.sh ${{ inputs.image }} ${{ inputs.tag }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Publish image
        run: |
          echo "Publishing image"
          PUBLIC_IMAGE_NAME="${{ inputs.registry }}/${{ github.event.repository.full_name }}/${{ inputs.image }}:${{ inputs.tag }}"
          docker tag ${{ inputs.image }}:${{ inputs.tag }} $PUBLIC_IMAGE_NAME
          docker rmi ${{ inputs.image }}:${{ inputs.tag }}
          docker push $PUBLIC_IMAGE_NAME