---

name: "Debug Action"

on:
  push:
  pull_request:
  pull_request_review:
  pull_request_review_comment:
  pull_request_target:
  fork:
  create:
  delete:
  label:
  issues:
  branch_protection_rule:
  deployment:
  deployment_status:
  discussion:
  discussion_comment:
  issue_comment:
  gollum:
  merge_group:
  milestone:
  page_build:
  project:
  project_card:
  project_column:
  public:
  registry_package:
  release:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print environment
        uses: hmarr/debug-action@v2
      - name: print github_event
        run: cat $GITHUB_EVENT_PATH
