---

name: "Debug Action"

on:
  push:
  pull_request:
  pull_request_review:
  pull_request_review_comment:
  pull_request_target:
  fork:
  create:
  delete:
  label:
  issues:
  branch_protection_rule:
  deployment:
  deployment_status:
  discussion:
  discussion_comment:
  issue_comment:
  gollum:
  merge_group:
  milestone:
  page_build:
  project:
  project_card:
  project_column:
  public:
  registry_package:
  release:

jobs:
  print_event_details:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print Event details
        run: |
          echo "GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME}"
          echo "GITHUB_EVENT_CREATE_REF_TYPE=${GITHUB_EVENT_CREATE_REF_TYPE}"
          echo "GITHUB_EVENT_PULL_REQUEST_HEAD_REF=${{ github.event.pull_request.head.ref }}"
        env:
          GITHUB_EVENT_CREATE_REF_TYPE: ${{ github.event.pull_request.head.ref }}

  print_env:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment
        uses: hmarr/debug-action@v2.1.0

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: print github event
        run: echo ${GITHUB_EVENT_CONTEXT}
        env:
          GITHUB_EVENT_CONTEXT: ${{ toJson(github.event) }}