---

name: "Debug Action"

on:
  push:
  pull_request:
  pull_request_review:
  pull_request_review_comment:
  pull_request_target:
  fork:
  create:
  delete:
  label:
  issues:
  branch_protection_rule:
  deployment:
  deployment_status:
  discussion:
  discussion_comment:
  issue_comment:
  gollum:
  merge_group:
  milestone:
  page_build:
  project:
  project_card:
  project_column:
  public:
  registry_package:
  release:

jobs:
  print_event_details:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print Event details
        run: |
          echo "GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME}"
          echo "📌 Event github.event context"
          # https://docs.github.com/en/webhooks/webhook-events-and-payloads#push
          echo "after: ${{ github.event.after }}"
          echo "before: ${{ github.event.before }}"
          echo "base_ref: ${{ github.event.base_ref }}"
          echo "commits.author.name: ${{ github.event.commits.author.name }}"
          echo "compare: ${{ github.event.compare }}"
          echo "created: ${{ github.event.created }}"
          echo "deleted: ${{ github.event.deleted }}"
          echo "description: ${{ github.event.description }}"
          echo "forced: ${{ github.event.forced }}"
          echo "head_commit.author.name: ${{ github.event.head_commit.author.name }}"
          echo "pusher.name: ${{ github.event.pusher.name }}"
          echo "ref: ${{ github.event.ref }}"
          echo "repository.full_name: ${{ github.event.repository.full_name }}"
          echo "sender.login: ${{ github.event.sender.login }}"
          # https://docs.github.com/en/webhooks/webhook-events-and-payloads#create
          echo "description: ${{ github.event.description }}"
          echo "master_branch: ${{ github.event.master_branch }}"
          echo "pusher_type: ${{ github.event.pusher_type }}"
          echo "ref_type: ${{ github.event.ref_type }}"

  print_env:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment
        uses: hmarr/debug-action@v2.1.0

      - name: Dump GitHub context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: print github event
        run: echo ${GITHUB_EVENT_CONTEXT}
        env:
          GITHUB_EVENT_CONTEXT: ${{ toJson(github.event) }}
