---

name: "Debug Action"

on:
  pull_request:
    branches: [ dev, main]
    types: [ closed ]
  push:
    # tags: [ v* ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print environment
        uses: hmarr/debug-action@v2
      - name: print github_event
        run: cat $GITHUB_EVENT_PATH
