---

name: "Docker CI"

on:
  pull_request:
    branches: [ dev ]
  push:
    branches: [ nrf-codespace ]
env:
  UBUNTU_BASE_IMAGE: tigitlabs/ubuntu-base:latest
  NRF_USER_UID: 1000
  NRF_USER_GID: 1000
  NRF_USER: vscode

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      ubuntu-base: ${{ steps.filter.outputs.ubuntu-base }}
      nrf-docker-image: ${{ steps.filter.outputs.nrf-docker-image }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          ubuntu-base:
            - '.devcontainer/ubuntu-base/**'
          nrf-docker-image:
            - '.devcontainer/nrf-docker/**'
  build-and-push-ubuntu-base:
    needs: changes
    if: ${{ needs.changes.outputs.ubuntu-base == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Build the Ubuntu base image
        run: |
          docker build \
          --file .devcontainer/ubuntu-base/Dockerfile \
          --tag ghcr.io/tigitlabs/ubuntu-base \
          .devcontainer/ubuntu-base/

      - name: Login to GitHub Container Registry
        if: ${{ !env.ACT }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Publish image
        if: ${{ !env.ACT }}
        run: |
          docker push ghcr.io/tigitlabs/ubuntu-base

  build-and-push-nrf-docker-image:
    needs: changes
    if: ${{ needs.changes.outputs.nrf-docker-image == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Build the nrf-docker image
        run: |
          docker build \
          --file .devcontainer/nrf-docker/Dockerfile \
          --tag ghcr.io/tigitlabs/nrf-docker \
          .devcontainer/nrf-docker/

      - name: Ensure clang-format works
        run: |
          docker run \
          --rm \
          --user $NRF_USER \
          ghcr.io/tigitlabs/nrf-docker:latest \
          clang-format --version

      - name: Ensure west works
        run: |
          docker run \
          --rm \
          --user $NRF_USER \
          ghcr.io/tigitlabs/nrf-docker:latest \
          west --version

      - name: Ensure nrfutil installation works
        run: |
          docker run \
          --rm \
          --user $NRF_USER \
          ghcr.io/tigitlabs/nrf-docker:latest \
          nrfutil toolchain-manager list

      - name: Ensure nrfjprog works
        run: |
          docker run \
          --rm \
          --user $NRF_USER \
          ghcr.io/tigitlabs/nrf-docker:latest \
          nrfjprog -v

      - name: Build asset_tracker_v2 application
        run: | 
          docker run \
          --rm \
          --user $NRF_USER \
          --workdir /workspace/nrf/applications/asset_tracker_v2 \
          ghcr.io/tigitlabs/nrf-docker \
          west build -b nrf9160dk_nrf9160ns --build-dir /workspace/nrf/applications/asset_tracker_v2/build -- -DEXTRA_CFLAGS="-Werror -Wno-dev"

      - name: Login to GitHub Container Registry
        if: ${{ !env.ACT }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Publish image
        if: ${{ !env.ACT }}
        run: |
          docker push ghcr.io/tigitlabs/nrf-docker

  build-and-push-nrf-codespace-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Build the nrf-codespace image
        run: |
          docker build \
          --file .devcontainer/nrf-codespace/Dockerfile \
          --tag ghcr.io/tigitlabs/nrf-codespace \
          .devcontainer/nrf-codespace/

      - name: Login to GitHub Container Registry
        if: ${{ !env.ACT }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Publish image
        if: ${{ !env.ACT }}
        run: |
          docker push ghcr.io/tigitlabs/nrf-codespace





  #     # Create build directory and set permissions
  #     - name: Create build directory
  #       run: |
  #         mkdir -p "$PWD/temp"
  #         sudo chown -R $NRF_USER_UID:$NRF_USER_GID "$PWD/temp"
