---

name: "Docker CI"

on:
  pull_request:
    branches: [ dev ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t tigitlabs/nrf-docker:latest -f .devcontainer/nrf-docker/Dockerfile .devcontainer/nrf-docker/
      - name: Build asset_tracker_v2 application
        run: |
          docker run --rm \
            -v ${PWD}:/workdir/project \
            -w /workdir/nrf/applications/asset_tracker_v2 \
            tigitlabs/nrf-docker:latest \
              west build -b nrf9160dk_nrf9160ns --build-dir /workdir/project/build -- -DEXTRA_CFLAGS="-Werror -Wno-dev"
      # - uses: actions/upload-artifact@v3
      #   with:
      #     if-no-files-found: error
      #     name: asset_tracker_v2
      #     path: |
      #       /workdir/project/build/zephyr/merged.hex
      #       /workdir/project/build/zephyr/app_update.bin

      - name: Ensure clang-format works
        run: |
          docker run --rm tigitlabs/nrf-docker:latest clang-format --version

      # - name: Ensure nrfjprog works
      #   run: |
      #     docker run --rm nrf-docker:latest nrfjprog -v

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: tigitlabs
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Publish image
        run: |
          docker images
          docker push tigitlabs/nrf-docker:latest
