---

name: "Docker CI"

on:
  pull_request:
    branches: [ dev ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t nrf -f .devcontainer/nrf-docker/Dockerfile .devcontainer/nrf-docker/
