---

name: "Build nrf-docker image"

on:
  # workflow_dispatch:
  push:
    paths:
     - '.devcontainer/nrf-docker/**'
     - '.github/workflows/docker-build-nrf-docker.yml'
 
env:
  ARTIFACTS_DIR: ~/artifacts/nrf-docker

jobs:

  build-nrf-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create artifact directory
        run: |
          mkdir nrf-docker-artifacts

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build the nrf-docker image and save it as a tarball
        run: |
          docker build \
          --file .devcontainer/nrf-docker/Dockerfile \
          --tag tigitlabs/nrf-docker:$(date +%s) \
          --output type=tar,dest=nrf-docker-artifacts/nrf-docker.tar \
          .devcontainer/nrf-docker/

      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: nrf-docker
          path: nrf-docker-artifacts/nrf-docker.tar
          if-no-files-found: error

      - name: check artifact size
        run: |
          du -sh nrf-docker-artifacts/nrf-docker.tar


  run-container-tests:
    runs-on: ubuntu-latest
    needs: build-nrf-docker-image
    steps:
      - uses: actions/checkout@v3
      - name: Load the nrf-docker artifact
        uses: actions/download-artifact@v3
        with:
          name: nrf-docker

      - name: check artifact size
        run: |
          echo "ls -la"
          ls -la
          echo "pwd"
          echo "cat the tar"
          cat nrf-docker.tar
          pwd

      - name: Load the nrf-docker image
        run: docker load --input nrf-docker.tar

      - name: Run the nrf-docker container
        run: docker run --rm nrf-docker west --version
