---

name: "Docker CI"

on:
  pull_request:
    branches: [ dev ]
  push:
    branches: [ nrf-codespace ]
env:
  UBUNTU_BASE_IMAGE: tigitlabs/ubuntu-base:latest
  NRF_USER_UID: 1000
  NRF_USER_GID: 1000
  NRF_USER: vscode

jobs:
  build-and-push-ubuntu-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Build the Ubuntu base image
        run: |
          docker build \
          --file .devcontainer/ubuntu-base/Dockerfile \
          --tag ghcr.io/tigitlabs/ubuntu-base \
          .devcontainer/ubuntu-base/

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Publish image
        run: |
          docker push ghcr.io/tigitlabs/ubuntu-base

  build-and-push-nrf-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Build the nrf-docker image
        run: |
          docker build \
          --file .devcontainer/nrf-docker/Dockerfile \
          --tag ghcr.io/tigitlabs/nrf-docker \
          .devcontainer/nrf-docker/

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Publish image
        run: |
          docker push ghcr.io/tigitlabs/nrf-docker

  build-and-push-nrf-codespace-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Build the nrf-codespace image
        run: |
          docker build \
          --file .devcontainer/nrf-codespace/Dockerfile \
          --tag ghcr.io/tigitlabs/nrf-codespace \
          .devcontainer/nrf-codespace/

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Publish image
        run: |
          docker push ghcr.io/tigitlabs/nrf-codespace


  # docker-build-and-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Build the Ubuntu base image
  #       run: |
  #         docker build \
  #         -t $UBUNTU_BASE_IMAGE \
  #         -f .devcontainer/ubuntu-base/Dockerfile .devcontainer/ubuntu-base/

  #     - name: Build the Docker image
  #       run: |
  #         docker build \
  #         -t tigitlabs/nrf-docker:latest \
  #         -f .devcontainer/nrf-docker/Dockerfile .devcontainer/nrf-docker/

  #     - name: Ensure nrfjprog works
  #       run: |
  #         docker run \
  #         --rm \
  #         --user $NRF_USER \
  #         tigitlabs/nrf-docker:latest \
  #         nrfjprog -v

  #     - name: Ensure nrfutil installation works
  #       run: |
  #         docker run \
  #         --rm \
  #         --user $NRF_USER \
  #         tigitlabs/nrf-docker:latest \
  #         nrfutil toolchain-manager list

  #     - name: Ensure clang-format works
  #       run: |
  #         docker run \
  #         --rm \
  #         --user $NRF_USER \
  #         tigitlabs/nrf-docker:latest \
  #         clang-format --version

  #     - name: Ensure west works
  #       run: |
  #         docker run \
  #         --rm \
  #         --user $NRF_USER \
  #         tigitlabs/nrf-docker:latest \
  #         west --version
  #     # Printing some information about the current environment
  #     - name: Print environment information
  #       run: |
  #         whoami && id \
  #         && echo "ACTIONS_USER_UID: $ACTIONS_USER_UID" \
  #         && echo "ACTIONS_USER_GID: $ACTIONS_USER_GID"

  #     # Create build directory and set permissions
  #     - name: Create build directory
  #       run: |
  #         mkdir -p "$PWD/temp"
  #         sudo chown -R $NRF_USER_UID:$NRF_USER_GID "$PWD/temp"

  #     - name: Build asset_tracker_v2 application
  #       run: | 
  #         docker run \
  #         --rm \
  #         --user $NRF_USER \
  #         --volume ${PWD}/temp:/workdir/project \
  #         --workdir /workdir/nrf/applications/asset_tracker_v2 \
  #         tigitlabs/nrf-docker \
  #         west build -b nrf9160dk_nrf9160ns --build-dir /workdir/project/ -- -DEXTRA_CFLAGS="-Werror -Wno-dev"

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: tigitlabs
  #         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  #     - name: Publish image
  #       run: |
  #         docker images
  #         docker push tigitlabs/nrf-docker:latest
