---

name: "Build nrf-docker image"

on:
  workflow_dispatch:
  push:
    #paths:
     # - ".devcontainer/nrf-docker/**"
env:
  ARTIFACTS_DIR: ~/artifacts/nrf-docker

jobs:

  build-nrf-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create artifact directory
        run: mkdir -p $ARTIFACTS_DIR
      - name: Build the nrf-docker image and save it as a tarball
        run: |
          docker build \
          --file .devcontainer/nrf-docker/Dockerfile \
          --tag ghcr.io/tigitlabs/nrf-docker \
          --output type=tar,dest=${ARTIFACTS_DIR}/nrf-docker.tar \
          .devcontainer/nrf-docker/

      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: nrf-docker
          path: $ARTIFACTS_DIR/nrf-docker.tar

  run-container-tests:
    runs-on: ubuntu-latest
    needs: build-nrf-docker-image
    steps:
      - uses: actions/checkout@v3
      - name: Load the nrf-docker artifact
        uses: actions/download-artifact@v3
        with:
          name: nrf-docker

      - name: Load the nrf-docker image
        run: docker load --input ${ARTIFACTS_DIR}/nrf-docker.tar

      - name: Run the nrf-docker container
        run: docker run --rm nrf-docker west --version