---

name: "Docker-Build-Publish"

on:
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

env:
  NRF_USER: vscode

jobs:

  build-and-push-ubuntu-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Build the Ubuntu base image
        run: |
          docker build \
          --file .devcontainer/ubuntu-base/Dockerfile \
          --tag tigitlabs/ubuntu-base \
          .devcontainer/ubuntu-base/

      - name: Login to GitHub Container Registry
        if: ${{ !env.ACT }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Publish image
        if: ${{ !env.ACT }}
        run: |
          docker tag tigitlabs/ubuntu-base ghcr.io/tigitlabs/ubuntu-base:dev
          docker tag tigitlabs/ubuntu-base ghcr.io/tigitlabs/ubuntu-base:latest
          docker tag tigitlabs/ubuntu-base ghcr.io/tigitlabs/ubuntu-base
          docker rmi tigitlabs/ubuntu-base
          docker push ghcr.io/tigitlabs/ubuntu-base --all-tags

  build-and-push-nrf-docker-image:
    needs: [ build-and-push-ubuntu-base ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Build the nrf-docker image
        run: |
          docker build \
          --file .devcontainer/nrf-docker/Dockerfile \
          --tag tigitlabs/nrf-docker \
          .devcontainer/nrf-docker/

      - name: Ensure clang-format works
        run: |
          docker run \
          --rm \
          tigitlabs/nrf-docker \
          clang-format --version

      - name: Ensure west works
        run: |
          docker run \
          --rm \
          tigitlabs/nrf-docker \
          west --version

      - name: Ensure nrfutil installation works
        run: |
          docker run \
          --rm \
          tigitlabs/nrf-docker \
          nrfutil toolchain-manager list

      - name: Login to GitHub Container Registry
        if: ${{ !env.ACT }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Publish image
        if: ${{ !env.ACT }}
        run: |
          docker tag tigitlabs/nrf-docker ghcr.io/tigitlabs/nrf-docker:dev
          docker tag tigitlabs/nrf-docker ghcr.io/tigitlabs/nrf-docker:latest
          docker tag tigitlabs/nrf-docker ghcr.io/tigitlabs/nrf-docker
          docker rmi tigitlabs/nrf-docker
          docker push ghcr.io/tigitlabs/nrf-docker --all-tags

  build-and-push-nrf-docker-ci-image:
    needs: [ build-and-push-nrf-docker-image ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Build the nrf-docker image
        run: |
          docker build \
          --file .devcontainer/nrf-docker/ci.Dockerfile \
          --tag tigitlabs/nrf-docker-ci \
          .devcontainer/nrf-docker/

      - name: Ensure clang-format works
        run: |
          docker run \
          --rm \
          tigitlabs/nrf-docker-ci \
          clang-format --version

      - name: Ensure west works
        run: |
          docker run \
          --rm \
          tigitlabs/nrf-docker-ci \
          west --version

      - name: Ensure nrfutil installation works
        run: |
          docker run \
          --rm \
          tigitlabs/nrf-docker-ci \
          nrfutil toolchain-manager list

      - name: Build asset_tracker_v2 application
        run: | 
          docker run \
          --rm \
          --workdir /workspace/nrf/applications/asset_tracker_v2 \
          tigitlabs/nrf-docker-ci \
          west build -b nrf9160dk_nrf9160ns --build-dir /workspace/nrf/applications/asset_tracker_v2/build -- -DEXTRA_CFLAGS="-Werror -Wno-dev"

      - name: Login to GitHub Container Registry
        if: ${{ !env.ACT }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Publish image
        if: ${{ !env.ACT }}
        run: |
          docker tag tigitlabs/nrf-docker-ci ghcr.io/tigitlabs/nrf-docker-ci:dev
          docker tag tigitlabs/nrf-docker-ci ghcr.io/tigitlabs/nrf-docker-ci:latest
          docker tag tigitlabs/nrf-docker-ci ghcr.io/tigitlabs/nrf-docker-ci
          docker rmi tigitlabs/nrf-docker-ci
          docker push ghcr.io/tigitlabs/nrf-docker-ci --all-tags


  build-and-push-nrf-codespace-image:
    needs: [ build-and-push-nrf-docker-image ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Build the nrf-codespace image
        run: |
          docker build \
          --file .devcontainer/nrf-codespace/Dockerfile \
          --tag tigitlabs/nrf-codespace \
          .devcontainer/nrf-codespace/

      - name: Ensure nrfjprog works
        run: |
          docker run \
          --rm \
          tigitlabs/nrf-codespace \
          nrfjprog -v

      - name: Login to GitHub Container Registry
        if: ${{ !env.ACT }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Publish image
        if: ${{ !env.ACT }}
        run: |
          docker tag tigitlabs/nrf-codespace ghcr.io/tigitlabs/nrf-codespace:dev
          docker tag tigitlabs/nrf-codespace ghcr.io/tigitlabs/nrf-codespace:latest
          docker tag tigitlabs/nrf-codespace ghcr.io/tigitlabs/nrf-codespace
          docker rmi tigitlabs/nrf-codespace
          docker push ghcr.io/tigitlabs/nrf-codespace --all-tags
