---

name: "Docker CI"

on:
  pull_request:
    branches: [ dev ]
env:
  UBUNTU_BASE_IMAGE: tigitlabs/ubuntu-base:latest
  NON_ROOT_USER: $(id -u):$(id -g)
  LOCAL_USER: vscode
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Ubuntu base image
        run: |
          docker build \
          -t $UBUNTU_BASE_IMAGE \
          -f .devcontainer/ubuntu-base/Dockerfile .devcontainer/ubuntu-base/

      - name: Build the Docker image
        run: |
          docker build \
          -t tigitlabs/nrf-docker:latest \
          -f .devcontainer/nrf-docker/Dockerfile .devcontainer/nrf-docker/

      - name: Ensure nrfjprog works
        run: |
          docker run \
          --rm \
          --user $LOCAL_USER \
          tigitlabs/nrf-docker:latest \
          nrfjprog -v

      - name: Ensure clang-format works
        run: |
          docker run \
          --rm \
          --user $LOCAL_USER \
          tigitlabs/nrf-docker:latest \
          clang-format --version

      - name: Ensure nrfutil installation works
        run: |
          docker run \
          --rm \
          --user $LOCAL_USER \
          tigitlabs/nrf-docker:latest \
          nrfutil toolchain-manager list

      - name: Build asset_tracker_v2 application
        run: | 
          docker run \
          --rm \
          --user root \
          --volume ${PWD}:/workdir/project \
          --workdir /workdir/nrf/applications/asset_tracker_v2 \
          tigitlabs/nrf-docker \
          west build -b nrf9160dk_nrf9160ns --build-dir /workdir/project/build -- -DEXTRA_CFLAGS="-Werror -Wno-dev"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: tigitlabs
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Publish image
        run: |
          docker images
          docker push tigitlabs/nrf-docker:latest
