---

name: "Makefile-CI"

on:
  pull_request:
    branches: [ dev ]

jobs:

  makefile-ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install devcontainer cli
        run: |
          npm install -g @devcontainers/cli
          devcontainer --version

      - name: Install nectos act
        run: |
          cd /
          curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
          act --version

      - name: Make sure the Makefile can be used
        run: make

      - name: make github-action-list
        run: make github-action-list

      - name: github-action-smoke-base-ubuntu
        run: make github-action-smoke-base-ubuntu
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: github-action-smoke-test
        run: make github-action-smoke-test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
