---

name: "Makefile-CI"

on:
  pull_request:
    branches: [ dev, main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  makefile-sanity-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install devcontainer cli
        run: |
          npm install -g @devcontainers/cli
          devcontainer --version

      - name: Install nectos act
        run: |
          cd /
          curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
          act --version

      - name: Make sure the Makefile can be used
        run: make

      - name: Run make help
        run: make help

      - name: Run make github-action-list
        run: make github-action-list

      - name: Run make github-action-markdown-lint
        run: make github-action-markdown-lint

  makefile-local-build:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ github.actor }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install devcontainer cli
        run: |
          npm install -g @devcontainers/cli
          devcontainer --version

      - name: Build base-ubuntu
        run: make build-base-ubuntu

      - name: Test base-ubuntu
        run: make test-base-ubuntu

      - name: Build base-nrf
        run: make build-base-nrf

      - name: Test base-nrf
        run: make test-base-nrf

      - name: Build nrf-ci
        run: make build-nrf-ci

      - name: Test nrf-ci
        run: make test-nrf-ci

      - name: Build nrf-devcontainer
        run: make build-nrf-devcontainer

      - name: Test nrf-devcontainer
        run: make test-nrf-devcontainer

      - name: Run make build-all
        run: make build-all

      - name: Show the build result
        run: docker images

  makefile-ci-run:
    # This is a redundant job, but it is here to make sure that the target is running
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ github.actor }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install devcontainer cli
        run: |
          npm install -g @devcontainers/cli
          devcontainer --version

      - name: Run make makefile-ci
        run: make makefile-ci