---

name: "Publish-Images"

on:
  pull_request:
    branches: [ dev, main]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-tags:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag_name.outputs.tag }}
    steps:
      - name: Get tags
        id: get_tag_name
        run: |
          if [[ "${{ github.event.ref_type }}" == 'tag' ]]; then
            echo "Tag event detected"
            # echo "tag=$(echo "${{ github.event.ref }}" | grep -oP 'refs/tags/\K(.+)')"
            tag=${{ github.event.ref }}
            # Check if the tag is a semver tag
            if [[ $tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
              echo "tag detected: $tag"
              echo "tag=$tag" >> $GITHUB_OUTPUT
              echo "Set the tag to: $tag"
            else
              echo "tag is not a semver tag"
              exit 1
            fi
          fi
          if [[ "${{ github.ref }}" == "refs/heads/"* ]]; then
            echo "Branch event detected"
            tag=$(echo "${{ github.ref }}" | grep -oP 'refs/heads/\K(.+)')
            echo "tag=$tag" >> $GITHUB_OUTPUT
            echo "Set the tag to: $tag"
          fi
          if [[ "${{ github.event.pull_request.state }}" == "open" ]]; then
            echo "Pull request open event detected"
            tag=${{ github.event.pull_request.head.ref }}
            echo "tag=$tag" >> $GITHUB_OUTPUT
            echo "Set the tag to: $tag"
          fi
          echo "Tag: ${tag}"

  build-test-push:
    needs: [ get-tags ]
    runs-on: ubuntu-latest
    env:
      TAG: ${{needs.get-tags.outputs.tag}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      IMAGE_NAME: base-ubuntu
      REGISTRY: ghcr.io
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Install devcontainer cli
        run: |
          npm install -g @devcontainers/cli
          devcontainer --version

      - name: Build Test and Push
        id: build-test-push
        uses: ./.github/actions/build-test-push.yml
        with:
          image: ${{ env.IMAGE_NAME }}
          tag: ${TAG}
          registry: ${{ env.REGISTRY }}
