---

name: "Publish-Images"

on:
  pull_request:
    branches: [ dev, main]
    types: [ closed ]
  push:
    tags: [ v* ]
jobs:

  get-tags:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag_name.outputs.tag }}
    steps:
      - name: Get tags
        id: get_tag_name
        run: |
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            echo "tag=$(echo "${{ github.ref }}" | grep -oP 'refs/tags/\K(.+)')" >> $GITHUB_OUTPUT
          fi
          if [[ "${{ github.ref }}" == "refs/heads/"* ]]; then
            echo "tag=$(echo "${{ github.ref }}" | grep -oP 'refs/heads/\K(.+)')" >> $GITHUB_OUTPUT
          fi

  build-and-push-base-ubuntu:
    needs: [ get-tags ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Install devcontainer cli
        run: |
          npm install -g @devcontainers/cli
          devcontainer --version

      - name: Smoke test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: smoke_test
        uses: ./.github/actions/smoke-test
        with:
          image: base-ubuntu
          variant: jammy

      - name: Build the Ubuntu base image
        env:
          TAG: ${{needs.get-tags.outputs.tag}}
        run: |
          export VARIANT=jammy
          devcontainer build \
          --workspace-folder src/base-ubuntu/ \
          --image-name base-ubuntu
          echo "Applying tag: ${TAG}"
          docker tag base-ubuntu ghcr.io/tigitlabs/base-ubuntu
          docker tag base-ubuntu ghcr.io/tigitlabs/base-ubuntu:${TAG}
          docker rmi base-ubuntu
          docker images

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Publish image
        if: ${{ !env.ACT }}
        run: |
          docker push ghcr.io/tigitlabs/base-ubuntu --all-tags

  build-and-push-base-nrf-image:
    needs: [ build-and-push-base-ubuntu, get-tags ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Install devcontainer cli
        run: |
          npm install -g @devcontainers/cli
          devcontainer --version

      - name: Smoke test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{needs.get-tags.outputs.tag}}
        id: smoke_test
        uses: ./.github/actions/smoke-test
        with:
          image: base-nrf
          variant: $TAG

      - name: Build the base-nrf image
        env:
          TAG: ${{needs.get-tags.outputs.tag}}
        run: |
          export VARIANT=dev
          devcontainer build \
          --workspace-folder src/base-nrf/ \
          --image-name base-nrf
          docker tag base-nrf ghcr.io/tigitlabs/base-nrf
          echo "Applying tag: ${TAG}"
          docker tag base-nrf ghcr.io/tigitlabs/base-nrf:${TAG}
          docker rmi base-nrf
          docker images

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Publish image
        if: ${{ !env.ACT }}
        run: |
          docker push ghcr.io/tigitlabs/base-nrf --all-tags
