---

name: "Publish-Images"

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ dev, main]
  push:
    branches: [ dev, main]
  create:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-tags:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag_name.outputs.tag }}
    steps:
      - name: Print environment
        uses: hmarr/debug-action@v2.1.0

      - name: Get tags
        id: get_tag_name
        run: |
          echo "action: ${{ github.event.action }}"
          echo "title: ${{ github.event.pull_request.title }}"
          echo "ℹ Pull request from ${{ github.event.pull_request.head.ref }} to ${{ github.event.pull_request.base.ref }}"
          echo "assignee.login: ${{ github.event.assignee.login }}"
          echo "merged: ${{ github.event.pull_request.merged }}"
          echo "number: ${{ github.event.pull_request.number }}"
          echo "state: ${{ github.event.pull_request.state }}"
          echo "base.ref": ${{ github.event.pull_request.base.ref }}
          echo "head.ref: ${{ github.event.pull_request.head.ref }}"
          echo "locked: ${{ github.event.pull_request.locked }}"
          echo "active_lock_reason: ${{ github.event.pull_request.active_lock_reason }}"
          echo "auto_merge.method: ${{ github.event.pull_request.auto_merge.method }}"
          if [[ "${{ github.event.pull_request.state }}" == "open" ]]; then
            echo "Pull request open event detected"
            echo "ℹ Pull request from ${{ github.event.pull_request.head.ref }} to ${{ github.event.pull_request.base.ref }}"
            # Using the head branch name as the tag
            tag=${{ github.event.pull_request.head.ref }}
            echo "Set the tag to: $tag"

          elif [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "Pull request merged event detected"
            tag=${{ github.event.pull_request.head.ref }}
            echo "Set the tag to: $tag"

          elif [[ "${{ github.event.ref_type }}" == 'tag' ]]; then
            echo "Tag event detected"
            # echo "tag=$(echo "${{ github.event.ref }}" | grep -oP 'refs/tags/\K(.+)')"
            tag=${{ github.event.ref }}
            # Check if the tag is a semver tag
            if [[ $tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
              echo "tag detected: $tag"
              echo "Set the tag to: $tag"
            else
              echo "tag is not a semver tag"
              exit 1
            fi
          fi
          if [[ -z "$tag" ]]; then
            echo "No tag found"
            exit 1
          else
            echo "Tag: ${tag}"
            echo "tag=$tag" >> $GITHUB_OUTPUT
          fi

  push-base-ubuntu:
    needs: get-tags
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-test-push.yml
    with:
      image: base-ubuntu
      tag: ${{ needs.get-tags.outputs.tag }}
  push-base-nrf:
    permissions:
      contents: read
      packages: write
    needs: 
      - get-tags
      - push-base-ubuntu
    uses: ./.github/workflows/build-test-push.yml
    with:
      image: base-nrf
      tag: ${{ needs.get-tags.outputs.tag }}
      base_image: ${{ needs.push-base-ubuntu.outputs.image_url }}

  push-nrf-ci:
    permissions:
      contents: read
      packages: write
    needs: 
      - get-tags
      - push-base-nrf
    uses: ./.github/workflows/build-test-push.yml
    with:
      image: nrf-ci
      tag: ${{ needs.get-tags.outputs.tag }}
      base_image: ${{ needs.push-base-nrf.outputs.image_url }}

  push-nrf-devcontainer:
    permissions:
      contents: read
      packages: write
    needs: 
      - get-tags
      - push-base-nrf
    uses: ./.github/workflows/build-test-push.yml
    with:
      image: nrf-devcontainer
      tag: ${{ needs.get-tags.outputs.tag }}
      base_image: ${{ needs.push-base-nrf.outputs.image_url }}
