---

name: "Publish-Images"

on:
  pull_request:
    branches: [ dev, main]
    types: [ closed ]
  create:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-tags:
    if: github.event.pull_request.merged == true || github.event.ref_type == 'tag'
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag_name.outputs.tag }}
    steps:
      - name: Get tags
        id: get_tag_name
        run: |
          if [[ "${{ github.event.ref_type }}" == 'tag' ]]; then
            echo "Tag event detected"
            # echo "tag=$(echo "${{ github.event.ref }}" | grep -oP 'refs/tags/\K(.+)')"
            tag=${{ github.event.ref }}
            # Check if the tag is a semver tag
            if [[ $tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
              echo "tag detected: $tag"
              echo "tag=$tag" >> $GITHUB_OUTPUT
              echo "Set the tag to: $tag"
            else
              echo "tag is not a semver tag"
              exit 1
            fi

          fi
          if [[ "${{ github.ref }}" == "refs/heads/"* ]]; then
            echo "Branch event detected"
            echo "tag=$(echo "${{ github.ref }}" | grep -oP 'refs/heads/\K(.+)')"
            echo "tag=$tag" >> $GITHUB_OUTPUT
            echo "Set the tag to: $tag"
          fi
          echo "Tag: ${tag}"

  build-and-push-base-ubuntu:
    if: github.event.pull_request.merged == true || github.event.ref_type == 'tag'
    needs: [ get-tags ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Install devcontainer cli
        run: |
          npm install -g @devcontainers/cli
          devcontainer --version

      - name: Smoke test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: smoke_test
        uses: ./.github/actions/smoke-test
        with:
          image: base-ubuntu
          variant: jammy

      - name: Build the Ubuntu base image
        env:
          TAG: ${{needs.get-tags.outputs.tag}}
        run: |
          export VARIANT=jammy
          devcontainer build \
          --workspace-folder src/base-ubuntu/ \
          --image-name base-ubuntu
          echo "Applying tag: ${TAG}"
          docker tag base-ubuntu ghcr.io/tigitlabs/base-ubuntu
          docker tag base-ubuntu ghcr.io/tigitlabs/base-ubuntu:${TAG}
          docker rmi base-ubuntu
          docker images

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Publish image
        if: ${{ !env.ACT }}
        run: |
          docker push ghcr.io/tigitlabs/base-ubuntu --all-tags

  build-and-push-base-nrf-image:
    if: github.event.pull_request.merged == true || github.event.ref_type == 'tag'
    needs: [ build-and-push-base-ubuntu, get-tags ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Install devcontainer cli
        run: |
          npm install -g @devcontainers/cli
          devcontainer --version

      - name: Smoke test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{needs.get-tags.outputs.tag}}
        id: smoke_test
        uses: ./.github/actions/smoke-test
        with:
          image: base-nrf
          variant: $TAG

      - name: Build the base-nrf image
        env:
          TAG: ${{needs.get-tags.outputs.tag}}
        run: |
          export VARIANT=dev
          devcontainer build \
          --workspace-folder src/base-nrf/ \
          --image-name base-nrf
          docker tag base-nrf ghcr.io/tigitlabs/base-nrf
          echo "Applying tag: ${TAG}"
          docker tag base-nrf ghcr.io/tigitlabs/base-nrf:${TAG}
          docker rmi base-nrf
          docker images

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Publish image
        if: ${{ !env.ACT }}
        run: |
          docker push ghcr.io/tigitlabs/base-nrf --all-tags

  build-and-push-nrf-ci-image:
    if: github.event.pull_request.merged == true || github.event.ref_type == 'tag'
    needs: [ build-and-push-base-nrf-image, get-tags ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Install devcontainer cli
        run: |
          npm install -g @devcontainers/cli
          devcontainer --version

      - name: Smoke test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{needs.get-tags.outputs.tag}}
        id: smoke_test
        uses: ./.github/actions/smoke-test
        with:
          image: base-nrf
          variant: $TAG

      - name: Build the nrf-ci image
        env:
          TAG: ${{needs.get-tags.outputs.tag}}
        run: |
          export VARIANT=dev
          devcontainer build \
          --workspace-folder src/nrf-ci/ \
          --image-name nrf-ci
          docker tag nrf-ci ghcr.io/tigitlabs/nrf-ci
          echo "Applying tag: ${TAG}"
          docker tag nrf-ci ghcr.io/tigitlabs/nrf-ci:${TAG}
          docker rmi nrf-ci
          docker images

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Publish image
        if: ${{ !env.ACT }}
        run: |
          docker push ghcr.io/tigitlabs/nrf-ci --all-tags

  build-and-push-nrf-devcontainer-image:
    if: github.event.pull_request.merged == true || github.event.ref_type == 'tag'
    needs: [ build-and-push-base-nrf-image, get-tags ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Install devcontainer cli
        run: |
          npm install -g @devcontainers/cli
          devcontainer --version

      - name: Smoke test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{needs.get-tags.outputs.tag}}
        id: smoke_test
        uses: ./.github/actions/smoke-test
        with:
          image: base-nrf
          variant: $TAG

      - name: Build the nrf-ci image
        env:
          TAG: ${{needs.get-tags.outputs.tag}}
        run: |
          export VARIANT=dev
          devcontainer build \
          --workspace-folder src/nrf-ci/ \
          --image-name nrf-ci
          docker tag nrf-ci ghcr.io/tigitlabs/nrf-ci
          echo "Applying tag: ${TAG}"
          docker tag nrf-ci ghcr.io/tigitlabs/nrf-ci:${TAG}
          docker rmi nrf-ci
          docker images

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Publish image
        if: ${{ !env.ACT }}
        run: |
          docker push ghcr.io/tigitlabs/nrf-ci --all-tags
