name: Smoke test "nrf-ci" build

on:
  push:
    branches:
    - main
  pull_request:
    paths:
      - src/base-nrf/**
      - .github/workflows/smoke-base-nrf.yaml
      - .github/actions/**
jobs:
  smoke-test-nrf-base:
    name: Smoke test nrf-ci
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      id: checkout
      uses: actions/checkout@v3

    - name: Smoke test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: smoke_test
      uses: ./.github/actions/smoke-test
      with:
        image: base-nrf
        variant: dev

  build-test-nrf-ci-image:
    name: west build test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v3

    - name: Setup devcontainer cli
      run: |
        export DOCKER_BUILDKIT=1
        echo "(*) Installing @devcontainer/cli"
        npm install -g @devcontainers/cli

    - name: Build nrf-ci image
      run: |
        echo "(*) Building nrf-ci image"
        export VARIANT=dev
        devcontainer build \
        --workspace-folder src/nrf-ci \
        --image-name nrf-ci

        --image nrf-ci --build-arg ZEPHYR_BASE=../zephyr --build-arg ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb --build-arg GNUARMEMB_TOOLCHAIN_PATH=/opt/gcc-arm-none-eabi-9-2020-q2-update --build-arg ZEPHYR_SDK_INSTALL_DIR=/opt/zephyr-sdk --build-arg ZEPHYR_SDK_VERSION=0.12.4 --build-arg ZEPHYR_SDK_DOWNLOAD_URL=
