name: Smoke test "nrf-devcontainer" build

on:
  push:
    branches:
    - main
  pull_request:
    paths:
      - src/nrf-devcontainer/**
      - .github/workflows/smoke-nrf-devcontainer.yaml
      - .github/actions/**

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke-test-nrf-devcontainer:
    name: Smoke test nrf-devcontainer
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      id: checkout
      uses: actions/checkout@v3

    - name: Smoke test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: smoke_test
      uses: ./.github/actions/smoke-test
      with:
        image: nrf-devcontainer
