name: Smoke test "base-ubuntu" build

on:
  push:
    branches:
    - main
  pull_request:
    paths:
      - src/base-ubuntu/**
      - .github/workflows/smoke-base-ubuntu.yaml
      - .github/actions/**
jobs:
  smoke-test:
    name: Smoke test
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      id: checkout
      uses: actions/checkout@v3

    - name: Smoke test Docker Build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: smoke_test_docker_build
      uses: ./.github/actions/smoke-test-docker
      with:
        image: base-ubuntu

    - name: Smoke test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: smoke_test
      uses: ./.github/actions/smoke-test
      with:
        image: base-ubuntu
